---
apiVersion: v1
kind: Service
metadata:
  name: orderer
spec:
  type: LoadBalancer
  selector:
    app: orderer
  ports:
  - protocol: TCP
    targetPort: 8040
    port: 8040
    nodePort: 30112
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: orderer
  labels:
    app: orderer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: orderer
  template:
    metadata:
      labels:
        app: orderer
    spec:
      volumes:
      - name: redis-storage
        persistentVolumeClaim:
          claimName: mypvc

      containers:
      - name: orderer
        image: hyperledger/fabric-orderer:2.2.1
        command: ["sh", "-c", "sleep 2 && orderer"]
        env:
        - name: ORDERER_GENERAL_LEDGERTYPE
          value: file
        - name: ORDERER_FILELEDGER_LOCATION
          value: /shared/hyperledger/orderer/ledger
        - name: ORDERER_GENERAL_BATCHTIMEOUT
          value: 1s
        - name: ORDERER_GENERAL_BATCHSIZE_MAXMESSAGECOUNT
          value: "10"
        - name: ORDERER_GENERAL_MAXWINDOWSIZE
          value: "1000"
        - name: ORDERER_GENERAL_LISTENADDRESS
          value: 0.0.0.0
        - name: ORDERER_GENERAL_LISTENPORT
          value: "8040"
        - name: ORDERER_GENERAL_LOGLEVEL
          value: debug
        - name: ORDERER_GENERAL_LOCALMSPDIR
          value: /shared/hyperledger/orderer/ordererOrganizations/example.com/orderers/orderer.example.com/msp
        - name: ORDERER_GENERAL_LOCALMSPID
          value: OrdererMSP
        - name: ORDERER_GENERAL_GENESISMETHOD
          value: file
        - name: ORDERER_GENERAL_GENESISFILE
          value: /shared/hyperledger/orderer/genesis.block
        - name: ORDERER_GENERAL_TLS_CERTIFICATE
          value: "/shared/hyperledger/orderer/ordererOrganizations/example.com/orderers/orderer.example.com/tls/server.crt"
        - name: ORDERER_GENERAL_TLS_PRIVATEKEY
          value: "/shared/hyperledger/orderer/ordererOrganizations/example.com/orderers/orderer.example.com/tls/server.key"
        - name: ORDERER_GENERAL_TLS_ROOTCAS
          value: "/shared/hyperledger/orderer/ordererOrganizations/example.com/orderers/orderer.example.com/tls/ca.crt"
        - name: ORDERER_GENERAL_CLUSTER_CLIENTCERTIFICATE
          value: "/shared/hyperledger/orderer/ordererOrganizations/example.com/orderers/orderer.example.com/tls/server.crt"
        - name: ORDERER_GENERAL_CLUSTER_CLIENTPRIVATEKEY
          value: "/shared/hyperledger/orderer/ordererOrganizations/example.com/orderers/orderer.example.com/tls/server.key"
        - name: ORDERER_GENERAL_CLUSTER_CLIENTPRIVATEKEY
          value: "/shared/hyperledger/orderer/ordererOrganizations/example.com/orderers/orderer.example.com/tls/ca.crt"
        - name: ORDERER_GENERAL_TLS_ENABLED
          value: "true"
        volumeMounts:
        - mountPath: /shared
          name: redis-storage
        ports:
        - containerPort: 8040
---
