---
apiVersion: v1
kind: Service
metadata:
  name: peer
spec:
  type: LoadBalancer
  selector:
    app: peer
  ports:
  - protocol: TCP
    targetPort: 9040
    port: 9040
    nodePort: 30112
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: peer
  labels:
    app: peer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: peer
  template:
    metadata:
      labels:
        app: peer
    spec:
      volumes:
      - name: redis-storage
        persistentVolumeClaim:
          claimName: filepvc

      containers:
      - name: peer
        image: hyperledger/fabric-peer:2.2.1
        command: ["sh", "-c", "sleep 1 && peer node start"]
        env:
        - name: CORE_PEER_NETWORKID
          value: dev
        - name: CORE_PEER_ID
          value: peer
        - name: CORE_PEER_ADDRESS
          value: peer:9040
        #CORE_PEER_GOSSIP_EXTERNALENDPOINT for Hyperledger Explorer
        - name: CORE_PEER_LISTENADDRESS
          value: 0.0.0.0:9040
        - name: CORE_PEER_CHAINCODEADDRESS
          value: peer:9041
        - name: CORE_PEER_CHAINCODELISTENADDRESS
          value: 0.0.0.0:9041
        - name: CORE_PEER_GOSSIP_EXTERNALENDPOINT
          value: peer:9040
        - name: CORE_PEER_GOSSIP_BOOTSTRAP
          value: peer:9040
        - name: CORE_PEER_GOSSIP_ENDPOINT
          value: peer:9040
        - name: CORE_PEER_GOSSIP_ORGLEADER
          value: "true"
        - name: CORE_PEER_GOSSIP_USELEADERELECTION
          value: "false"
        - name: CORE_VM_ENDPOINT
          value: "unix:///host/var/run/docker.sock"
        - name: CORE_PEER_LOCALMSPID
          value: Org1MSP
        - name: CORE_PEER_MSPCONFIGPATH
          value: /shared/hyperledger/peer/peerOrganizations/org1.example.com/peers/peer0.org1.example.com/msp/
        - name: CORE_PEER_FILESYSTEMPATH
          value: /shared/hyperledger/peer/ledger
        - name: FABRIC_LOGGING_SPEC
          value: info
        - name: CORE_PEER_PROFILE_ENABLED
          value: "true"
        - name: CORE_PEER_TLS_ENABLED
          value: "true"
        - name: CORE_PEER_TLS_CERT_FILE
          value: "/shared/hyperledger/peer/peerOrganizations/org1.example.com/peers/peer0.org1.example.com/tls/server.crt"
        - name: CORE_PEER_TLS_KEY_FILE
          value: "/shared/hyperledger/peer/peerOrganizations/org1.example.com/peers/peer0.org1.example.com/tls/server.key"
        - name: CORE_PEER_TLS_ROOTCERT_FILE
          value: "/shared/hyperledger/peer/peerOrganizations/org1.example.com/peers/peer0.org1.example.com/tls/ca.crt"
        - name: CORE_LEDGER_STATE_STATEDATABASE
          value: "goleveldb"
        volumeMounts:
        - mountPath: /shared
          name: redis-storage
        ports:
        - containerPort: 9040
