NodeOUs:
  Enable: true
  ClientOUIdentifier:
    Certificate: cacerts/159-122-186-71-30102-peer-ca.pem
    OrganizationalUnitIdentifier: client
  PeerOUIdentifier:
    Certificate: cacerts/159-122-186-71-30102-peer-ca.pem
    OrganizationalUnitIdentifier: peer
  AdminOUIdentifier:
    Certificate: cacerts/159-122-186-71-30102-peer-ca.pem
    OrganizationalUnitIdentifier: admin
  OrdererOUIdentifier:
    Certificate: cacerts/159-122-186-71-30102-peer-ca.pem
    OrganizationalUnitIdentifier: orderer
